server:
  host: 0.0.0.0
  port: 3601
fetch:
  interval_minutes: 10
  max_items: 500
  feeds:
  - https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
  - https://feeds.bbci.co.uk/news/rss.xml?edition=int
  - https://sanhua.himrr.com/daily-news/feed
  - https://feeds.washingtonpost.com/rss/world
  - https://www.theguardian.com/international/rss
  - https://feeds.bloomberg.com/technology/news.rss
  - https://feeds.washingtonpost.com/rss/technology
  - https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml
  - https://rss.nytimes.com/services/xml/rss/nyt/Opinion.xml
  - https://feeds.npr.org/1002/rss.xml
  use_article_page: true
  article_timeout_seconds: 15
  per_feed_limit: 5
ai:
  enabled: true
  base_url: https://api.aioec.tech/v1
  api_key: sk-WVWB2AVFwx0KdOrP0T7Askg7b9KL8C2mt0qxUkMBTwxFYLzF
  model: glm-4.6
  temperature: 0.2
  system_prompt: 你是一个中文内容编辑助手。请对RSS文章进行信息抽取与高质量中文摘要，并输出严格的JSON对象，字段必须为：title, link,
    pubDate, author, summary_text。其中：title为原文标题或优化后的标题；link为原始URL；pubDate为发布时间（原文给出即可）；author为作者（若未知可留空字符串）；summary_text为简洁、条理清晰的段落式中文总结。务必只输出JSON，不要任何解释或markdown。
  user_prompt_template: '标题: {title}

    链接: {link}

    发布时间: {pub_date}

    作者: {author}

    正文/摘要(可能包含HTML):

    {content}


    请只输出JSON，不要任何解释或markdown。'
telegram:
  enabled: true
  bot_token: 7698712513:AAEf4Fyjc4D4Kb9GFq3IJvCZ4-ptRIfcuu4
  chat_id: '-1002573195446'
logging:
  level: INFO
  file: logs/app.log
