server:
  host: 0.0.0.0
  port: 3601
fetch:
  interval_minutes: 10
  max_items: 500
  feeds:
  - https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
  - https://feeds.bbci.co.uk/news/rss.xml?edition=int
  use_article_page: true
  article_timeout_seconds: 15
  per_feed_limit: 2
ai:
  enabled: true
  base_url: https://api.aioec.tech/v1
  api_key: sk-WVWB2AVFwx0KdOrP0T7Askg7b9KL8C2mt0qxUkMBTwxFYLzF
  model: glm-4.6
  temperature: 0.2
telegram:
  enabled: true
  bot_token: 7212570576:AAGCtl7Xl42aiZgl024q8dJ5Ic2bLIinLDo
  chat_id: '-1002573195446'
logging:
  level: INFO
  file: logs/app.log
