# RSS-AI 配置示例

# 服务监听配置
server:
  host: 0.0.0.0
  port: 3601

# 抓取与存储配置
fetch:
  interval_minutes: 10     # 定时抓取间隔（分钟）
  max_items: 500           # 本地存储的文章上限（总量）
  feeds:                   # RSS 列表
    - https://hnrss.org/frontpage
    - https://rsshub.app/solidot/linux
  use_article_page: true   # 抓取原文网页并抽取正文后再送AI
  article_timeout_seconds: 15
  per_feed_limit: 20       # 单个RSS源每次抓取的最大条数（越新的优先）

# AI 接口配置（OpenAI 通用格式）
ai:
  enabled: true
  base_url: https://api.openai.com/v1
  api_key: "YOUR_API_KEY"
  model: gpt-4o-mini
  # 温度可选
  temperature: 0.2
  # 自定义提示词
  system_prompt: |
    你是一个中文内容编辑助手。请对RSS文章进行信息抽取与高质量中文摘要，并输出严格的JSON对象，字段必须为：title, link, pubDate, author, summary_text。其中：title为原文标题或优化后的标题；link为原始URL；pubDate为发布时间（原文给出即可）；author为作者（若未知可留空字符串）；summary_text为简洁、条理清晰的段落式中文总结。务必只输出JSON，不要任何解释或markdown。
  user_prompt_template: |
    标题: {title}
    链接: {link}
    发布时间: {pub_date}
    作者: {author}
    正文/摘要(可能包含HTML):
    {content}

    请只输出JSON，不要任何解释或markdown。

# Telegram 推送配置
telegram:
  enabled: false
  bot_token: "YOUR_TELEGRAM_BOT_TOKEN"
  chat_id: "@your_channel_or_chat_id"
  push_summary: false

# 运行时日志
logging:
  level: INFO
  file: logs/app.log
